In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [24]:
df = pd.read_csv(
    "Indicadores.csv",
    encoding="latin-1",
    sep=",",
    engine="python",
    skipinitialspace=True
)

In [26]:
df.head()

,ID,Riesgos,Unidad auditable,Unnamed: 3,Código proceso,Nombre proceso,Clasificación objetivo estratégico,Código objetivo estratégico,Nombre objetivo estratégico,Indicador,...,Febrero 2026,Unnamed: 1032,Unnamed: 1033,Unnamed: 1034,Unnamed: 1035,Marzo 2026,Unnamed: 1037,Unnamed: 1038,Unnamed: 1039,Unnamed: 1040
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Valor,Meta,Semáforo,Fecha Requerida de Medición,Periodo Medido,Valor,Meta,Semáforo,Fecha Requerida de Medición,Periodo Medido
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11331.0,NaN,NaN,NaN,NaN,Gestión Servicio de Urgencias,NaN,NaN,NaN,PORCENTAJE DE INGRESOS EFECTIVOS AL HUS DE PAC...,...,Sin medición,"51,00",NaN,2026-03-31,NaN,Sin medición,"51,00",NaN,2026-04-30,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11322.0,NaN,NaN,NaN,NaN,Gestión Servicio de Urgencias,NaN,NaN,NaN,PORCENTAJE DE PARTICIPACION DE REFERENCIA Y CO...,...,Sin medición,"10,00",NaN,2026-03-31,NaN,Sin medición,"10,00",NaN,2026-04-30,NaN

In [27]:
df.columns

Index(['ID', 'Riesgos', 'Unidad auditable', 'Unnamed: 3', 'Código proceso',
       'Nombre proceso', 'Clasificación objetivo estratégico',
       'Código objetivo estratégico', 'Nombre objetivo estratégico',
       'Indicador',
       ...
       'Febrero 2026', 'Unnamed: 1032', 'Unnamed: 1033', 'Unnamed: 1034',
       'Unnamed: 1035', 'Marzo 2026', 'Unnamed: 1037', 'Unnamed: 1038',
       'Unnamed: 1039', 'Unnamed: 1040'],
      dtype='object', length=1041)

In [28]:
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

In [29]:
df = df.dropna(how='all')

In [30]:
columnas_base = [
    'ID',
    'Unidad auditable',
    'Código proceso',
    'Nombre proceso',
    'Indicador'
]

In [31]:
columnas_meses = [col for col in df.columns if any(mes in col for mes in [
    'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
    'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'
])]

In [32]:
df_melt = df.melt(
    id_vars=columnas_base,
    value_vars=columnas_meses,
    var_name='fecha',
    value_name='valor'
)

In [33]:
df_melt = df_melt.dropna(subset=['valor'])

In [35]:
df_melt['fecha'] = pd.to_datetime(df_melt['fecha'], errors='coerce')

C:\Users\nicoi\AppData\Local\Temp\ipykernel_9048\50693997.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_melt['fecha'] = pd.to_datetime(df_melt['fecha'], errors='coerce')

In [36]:
df_melt.head()

,ID,Unidad auditable,Código proceso,Nombre proceso,Indicador,fecha,valor
0,NaN,NaN,NaN,NaN,NaN,NaT,Valor
1,11331.0,NaN,NaN,Gestión Servicio de Urgencias,PORCENTAJE DE INGRESOS EFECTIVOS AL HUS DE PAC...,NaT,Sin medición
3,11322.0,NaN,NaN,Gestión Servicio de Urgencias,PORCENTAJE DE PARTICIPACION DE REFERENCIA Y CO...,NaT,Sin medición
5,11324.0,NaN,NaN,Gestión Servicio de Urgencias,PORCENTAJE DE PERTINENCIA DE REMISIONES ACEPTA...,NaT,Sin medición
7,11305.0,Gestión Servicio de Urgencias,NaN,Gestión Servicio de Urgencias,TIEMPO PROMEDIO DE RESPUESTA A REFERENCIA Y CO...,NaT,Sin medición

In [37]:
for col in df.columns:
    print(col)

ID
Riesgos
Unidad auditable
Código proceso
Nombre proceso
Clasificación objetivo estratégico
Código objetivo estratégico
Nombre objetivo estratégico
Indicador
Clasificación
Código Indicador
Tipo
Estado
Unidad de medida
Periodicidad
Responsable Análisis
Responsable Operativo
Finalidad
Acumulación
Tipo de semáforo
Tipo de semaforización
Escala (Rojo - Conservar rango)
Escala (Verde - Conservar rango)
Escala (Rojo - Conservar rango).1
Escala (Rojo - Maximizar)
Escala (Amarillo - Maximizar)
Escala (Verde - Maximizar)
Escala (Verde - Minimizar)
Escala (Amarillo - Minimizar)
Escala (Rojo - Minimizar)
Tipo meta
Clase
Descripción
Área
ICONTEC
Observación
Criterios de calidad
Descripción de uso
Objetivos Institucionales
Ejes de acreditación
Modelo de atención
Táctico
Estratégico
Operativo
Aprobado Planeación
Fórmula
Fecha creación
Fecha válido
Fecha corte
Referentes
Relacionados
Responsables
Sistema riesgo
Unidad riesgo
ID variable
Código de la variable
Nombre Variable
Unidad de medida.1
Mínimo
Máximo
Desviación
Promedio
Rango
Varianza
Mediana
Enero 2010
Febrero 2010
Marzo 2010
Abril 2010
Mayo 2010
Junio 2010
Julio 2010
Agosto 2010
Septiembre 2010
Octubre 2010
Noviembre 2010
Diciembre 2010
Enero 2011
Febrero 2011
Marzo 2011
Abril 2011
Mayo 2011
Junio 2011
Julio 2011
Agosto 2011
Septiembre 2011
Octubre 2011
Noviembre 2011
Diciembre 2011
Enero 2012
Febrero 2012
Marzo 2012
Abril 2012
Mayo 2012
Junio 2012
Julio 2012
Agosto 2012
Septiembre 2012
Octubre 2012
Noviembre 2012
Diciembre 2012
Enero 2013
Febrero 2013
Marzo 2013
Abril 2013
Mayo 2013
Junio 2013
Julio 2013
Agosto 2013
Septiembre 2013
Octubre 2013
Noviembre 2013
Diciembre 2013
Enero 2014
Febrero 2014
Marzo 2014
Abril 2014
Mayo 2014
Junio 2014
Julio 2014
Agosto 2014
Septiembre 2014
Octubre 2014
Noviembre 2014
Diciembre 2014
Enero 2015
Febrero 2015
Marzo 2015
Abril 2015
Mayo 2015
Junio 2015
Julio 2015
Agosto 2015
Septiembre 2015
Octubre 2015
Noviembre 2015
Diciembre 2015
Enero 2016
Febrero 2016
Marzo 2016
Abril 2016
Mayo 2016
Junio 2016
Julio 2016
Agosto 2016
Septiembre 2016
Octubre 2016
Noviembre 2016
Diciembre 2016
Enero 2017
Febrero 2017
Marzo 2017
Abril 2017
Mayo 2017
Junio 2017
Julio 2017
Agosto 2017
Septiembre 2017
Octubre 2017
Noviembre 2017
Diciembre 2017
Enero 2018
Febrero 2018
Marzo 2018
Abril 2018
Mayo 2018
Junio 2018
Julio 2018
Agosto 2018
Septiembre 2018
Octubre 2018
Noviembre 2018
Diciembre 2018
Enero 2019
Febrero 2019
Marzo 2019
Abril 2019
Mayo 2019
Junio 2019
Julio 2019
Agosto 2019
Septiembre 2019
Octubre 2019
Noviembre 2019
Diciembre 2019
Enero 2020
Febrero 2020
Marzo 2020
Abril 2020
Mayo 2020
Junio 2020
Julio 2020
Agosto 2020
Septiembre 2020
Octubre 2020
Noviembre 2020
Diciembre 2020
Enero 2021
Febrero 2021
Marzo 2021
Abril 2021
Mayo 2021
Junio 2021
Julio 2021
Agosto 2021
Septiembre 2021
Octubre 2021
Noviembre 2021
Diciembre 2021
Enero 2022
Febrero 2022
Marzo 2022
Abril 2022
Mayo 2022
Junio 2022
Julio 2022
Agosto 2022
Septiembre 2022
Octubre 2022
Noviembre 2022
Diciembre 2022
Enero 2023
Febrero 2023
Marzo 2023
Abril 2023
Mayo 2023
Junio 2023
Julio 2023
Agosto 2023
Septiembre 2023
Octubre 2023
Noviembre 2023
Diciembre 2023
Enero 2024
Febrero 2024
Marzo 2024
Abril 2024
Mayo 2024
Junio 2024
Julio 2024
Agosto 2024
Septiembre 2024
Octubre 2024
Noviembre 2024
Diciembre 2024
Enero 2025
Febrero 2025
Marzo 2025
Abril 2025
Mayo 2025
Junio 2025
Julio 2025
Agosto 2025
Septiembre 2025
Octubre 2025
Noviembre 2025
Diciembre 2025
Enero 2026
Febrero 2026
Marzo 2026

In [38]:
df = df.loc[:, ~df.columns.str.contains('Escala')]
df = df.loc[:, ~df.columns.str.contains('Unnamed')]

In [39]:
columnas_base = [
    'ID',
    'Unidad auditable',
    'Código proceso',
    'Nombre proceso',
    'Indicador'
]

In [40]:
columnas_meses = [col for col in df.columns 
                  if any(mes in col for mes in [
                      'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                      'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'
                  ])]

In [41]:
df_melt = df.melt(
    id_vars=columnas_base,
    value_vars=columnas_meses,
    var_name='fecha',
    value_name='valor'
)

In [42]:
df_melt = df_melt[df_melt['valor'] != 'Sin medición']
df_melt = df_melt.dropna(subset=['valor'])

In [43]:
df_melt['fecha'] = pd.to_datetime(df_melt['fecha'], errors='coerce')

C:\Users\nicoi\AppData\Local\Temp\ipykernel_9048\50693997.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_melt['fecha'] = pd.to_datetime(df_melt['fecha'], errors='coerce')

In [44]:
df_melt['valor'] = pd.to_numeric(df_melt['valor'], errors='coerce')

In [45]:
df_melt.head()

     ID Unidad auditable Código proceso Nombre proceso Indicador fecha  valor
0   NaN              NaN            NaN            NaN       NaN   NaT    NaN
132 NaN              NaN            NaN            NaN       NaN   NaT    NaN
264 NaN              NaN            NaN            NaN       NaN   NaT    NaN
396 NaN              NaN            NaN            NaN       NaN   NaT    NaN
528 NaN              NaN            NaN            NaN       NaN   NaT    NaN

In [46]:
df = df.dropna(subset=['ID'])

In [47]:
df.head()

,ID,Riesgos,Unidad auditable,Código proceso,Nombre proceso,Clasificación objetivo estratégico,Código objetivo estratégico,Nombre objetivo estratégico,Indicador,Clasificación,...,Junio 2025,Julio 2025,Agosto 2025,Septiembre 2025,Octubre 2025,Noviembre 2025,Diciembre 2025,Enero 2026,Febrero 2026,Marzo 2026
2,11331.0,NaN,NaN,NaN,Gestión Servicio de Urgencias,NaN,NaN,NaN,PORCENTAJE DE INGRESOS EFECTIVOS AL HUS DE PAC...,Proceso,...,"67,58","73,45","73,96","67,07","75,61","65,56","79,23",Sin medición,Sin medición,Sin medición
4,11322.0,NaN,NaN,NaN,Gestión Servicio de Urgencias,NaN,NaN,NaN,PORCENTAJE DE PARTICIPACION DE REFERENCIA Y CO...,Proceso,...,"6,66",Sin medición,Sin medición,Sin medición,Sin medición,Sin medición,Sin medición,Sin medición,Sin medición,Sin medición
6,11324.0,NaN,NaN,NaN,Gestión Servicio de Urgencias,NaN,NaN,NaN,PORCENTAJE DE PERTINENCIA DE REMISIONES ACEPTA...,Proceso,...,"74,17","60,14","65,45","58,56","36,29","45,96","50,97",Sin medición,Sin medición,Sin medición
8,11305.0,NaN,Gestión Servicio de Urgencias,NaN,Gestión Servicio de Urgencias,NaN,NaN,NaN,TIEMPO PROMEDIO DE RESPUESTA A REFERENCIA Y CO...,Proceso,...,"7,06","4,59","4,20","4,24","4,70","3,23","4,22",Sin medición,Sin medición,Sin medición
10,11311.0,NaN,Gestión Servicio de Urgencias,NaN,Gestión Servicio de Urgencias,NaN,NaN,NaN,TIEMPO PROMEDIO DE RESPUESTA INSTITUCIONAL A L...,Proceso,...,"7,40","6,91","5,76","5,17","4,99","3,77","5,16",Sin medición,Sin medición,Sin medición

In [48]:
df_melt = df.melt(
    id_vars=[
        'ID',
        'Unidad auditable',
        'Código proceso',
        'Nombre proceso',
        'Indicador'
    ],
    value_vars=columnas_meses,
    var_name='fecha',
    value_name='valor'
)

In [49]:
df_melt = df_melt.dropna(subset=['valor'])
df_melt = df_melt[df_melt['valor'] != 'Sin medición']

In [50]:
df_melt.head()

,ID,Unidad auditable,Código proceso,Nombre proceso,Indicador,fecha,valor
848,4307.0,NaN,"00PU01-V3,","Atención al Paciente de Urgencias, Gestión Ser...",PROPORCION DE PACIENTES QUE REINGRESAN AL SERV...,Enero 2011,"0,00"
849,4309.0,NaN,"00PU01-V3,","Atención al Paciente de Urgencias, Gestión Ser...",PORCENTAJE DE MORTALIDAD EN URGENCIAS ANTES DE...,Enero 2011,"1,15"
851,4665.0,NaN,"00PU01-V3,","Atención al Paciente de Urgencias, Gestión Ser...",PORCENTAJE MORTALIDAD OBSTETRICA EN URGENCIAS ...,Enero 2011,"0,00"
869,4682.0,NaN,"00PU01-V3,","Atención al Paciente de Urgencias, Gestión Ser...",TOTAL DE PACIENTES ATENDIDOS EN URGENCIAS,Enero 2011,"1.126,00"
871,4684.0,NaN,"00PU01-V3,","Atención al Paciente de Urgencias, Gestión Ser...",NUMERO DE PACIENTES CLASIFICADOS COMO TRIAGE I,Enero 2011,"0,00"

In [51]:
meses = {
    'Enero': '01', 'Febrero': '02', 'Marzo': '03',
    'Abril': '04', 'Mayo': '05', 'Junio': '06',
    'Julio': '07', 'Agosto': '08', 'Septiembre': '09',
    'Octubre': '10', 'Noviembre': '11', 'Diciembre': '12'
}

def convertir_fecha(fecha):
    try:
        mes, año = fecha.split()
        return f"{año}-{meses[mes]}-01"
    except:
        return None

df_melt['fecha'] = df_melt['fecha'].apply(convertir_fecha)
df_melt['fecha'] = pd.to_datetime(df_melt['fecha'])

In [54]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:123456@127.0.0.1:3304/hospital_kpi")

In [55]:
engine.connect()

In [56]:
df_melt.to_sql('mediciones', con=engine, if_exists='replace', index=False)

5642

In [63]:
df_procesos = df_procesos.rename(columns={
    'Código proceso': 'codigo_proceso',
    'Nombre proceso': 'nombre_proceso'
})

In [64]:
df_procesos.columns

Index(['id_proceso', 'codigo_proceso', 'nombre_proceso'], dtype='object')

In [65]:
df_procesos.to_sql('procesos', con=engine, if_exists='append', index=False)

2

In [66]:
df_indicadores = df[[
    'ID',
    'Indicador',
    'Código proceso',
    'Código objetivo estratégico',
    'Periodicidad',
    'Unidad de medida'
]].drop_duplicates()

In [67]:
df_indicadores = df_indicadores.dropna(subset=['ID', 'Indicador'])

In [68]:
df_indicadores = df_indicadores.rename(columns={
    'ID': 'id_indicador',
    'Indicador': 'nombre_indicador',
    'Periodicidad': 'frecuencia',
    'Unidad de medida': 'unidad'
})

In [69]:
df_indicadores = df_indicadores.merge(
    df_procesos[['codigo_proceso', 'id_proceso']],
    left_on='Código proceso',
    right_on='codigo_proceso',
    how='left'
)

In [70]:
df_indicadores = df_indicadores.drop(columns=['Código proceso', 'codigo_proceso'])

In [71]:
df_obj = df[[
    'Código objetivo estratégico',
    'Nombre objetivo estratégico'
]].drop_duplicates().dropna()

df_obj['id_objetivo'] = range(1, len(df_obj)+1)

df_obj = df_obj.rename(columns={
    'Código objetivo estratégico': 'codigo_objetivo',
    'Nombre objetivo estratégico': 'nombre_objetivo'
})

In [72]:
df_indicadores = df_indicadores.merge(
    df_obj[['codigo_objetivo', 'id_objetivo']],
    left_on='Código objetivo estratégico',
    right_on='codigo_objetivo',
    how='left'
)

In [73]:
df_indicadores = df_indicadores.drop(columns=[
    'Código objetivo estratégico',
    'codigo_objetivo'
])

In [74]:
df_indicadores['meta'] = None

In [75]:
df_indicadores = df_indicadores[[
    'id_indicador',
    'nombre_indicador',
    'id_proceso',
    'id_objetivo',
    'frecuencia',
    'meta',
    'unidad'
]]

In [80]:
df_indicadores['id_objetivo'] = df_indicadores['id_objetivo'].astype(int)
df_indicadores['id_proceso'] = df_indicadores['id_proceso'].astype(int)
df_indicadores['id_indicador'] = df_indicadores['id_indicador'].astype(int)

In [81]:
df_indicadores[['id_objetivo']].drop_duplicates()

    id_objetivo
7             1
8             2
9             4
13            3

In [84]:
df_indicadores.to_sql('indicadores', con=engine, if_exists='append', index=False)

IntegrityError: (pymysql.err.IntegrityError) (1062, "Duplicate entry '4277' for key 'PRIMARY'")
[SQL: INSERT INTO indicadores (id_indicador, nombre_indicador, id_proceso, id_objetivo, frecuencia, meta, unidad) VALUES (%(id_indicador)s, %(nombre_indicador)s, %(id_proceso)s, %(id_objetivo)s, %(frecuencia)s, %(meta)s, %(unidad)s)]
[parameters: [{'id_indicador': 4277, 'nombre_indicador': 'TIEMPO PROMEDIO DE ESPERA PARA LA ATENCION EN URGENCIAS DEL PACIENTE CLASIFICADO COMO TRIAGE II', 'id_proceso': 1, 'id_objetivo': 1, 'frecuencia': 'Mensual', 'meta': None, 'unidad': 'Minutos'}, {'id_indicador': 4277, 'nombre_indicador': 'TIEMPO PROMEDIO DE ESPERA PARA LA ATENCION EN URGENCIAS DEL PACIENTE CLASIFICADO COMO TRIAGE II', 'id_proceso': 1, 'id_objetivo': 2, 'frecuencia': 'Mensual', 'meta': None, 'unidad': 'Minutos'}, {'id_indicador': 4277, 'nombre_indicador': 'TIEMPO PROMEDIO DE ESPERA PARA LA ATENCION EN URGENCIAS DEL PACIENTE CLASIFICADO COMO TRIAGE II', 'id_proceso': 1, 'id_objetivo': 4, 'frecuencia': 'Mensual', 'meta': None, 'unidad': 'Minutos'}, {'id_indicador': 4307, 'nombre_indicador': 'PROPORCION DE PACIENTES QUE REINGRESAN AL SERVICIO DE URGENCIAS EN MENOS DE 72 HORAS DESPUES DEL EGRESO', 'id_proceso': 1, 'id_objetivo': 1, 'frecuencia': 'Mensual', 'meta': None, 'unidad': 'Porcentaje'}, {'id_indicador': 4307, 'nombre_indicador': 'PROPORCION DE PACIENTES QUE REINGRESAN AL SERVICIO DE URGENCIAS EN MENOS DE 72 HORAS DESPUES DEL EGRESO', 'id_proceso': 1, 'id_objetivo': 2, 'frecuencia': 'Mensual', 'meta': None, 'unidad': 'Porcentaje'}, {'id_indicador': 4307, 'nombre_indicador': 'PROPORCION DE PACIENTES QUE REINGRESAN AL SERVICIO DE URGENCIAS EN MENOS DE 72 HORAS DESPUES DEL EGRESO', 'id_proceso': 1, 'id_objetivo': 4, 'frecuencia': 'Mensual', 'meta': None, 'unidad': 'Porcentaje'}, {'id_indicador': 4309, 'nombre_indicador': 'PORCENTAJE DE MORTALIDAD EN URGENCIAS ANTES DE LAS 24 HORAS', 'id_proceso': 1, 'id_objetivo': 3, 'frecuencia': 'Mensual', 'meta': None, 'unidad': 'Porcentaje'}, {'id_indicador': 4319, 'nombre_indicador': 'PORCENTAJE DE REMISIONES ACEPTADAS EN EL HUS', 'id_proceso': 2, 'id_objetivo': 1, 'frecuencia': 'Mensual', 'meta': None, 'unidad': 'Porcentaje'}  ... displaying 10 of 34 total bound parameter sets ...  {'id_indicador': 10450, 'nombre_indicador': 'TIEMPO PROMEDIO DE ESPERA PARA LA ATENCION EN URGENCIAS DEL PACIENTE CLASIFICADO COMO TRIAGE II (UFZ)', 'id_proceso': 1, 'id_objetivo': 2, 'frecuencia': 'Mensual', 'meta': None, 'unidad': 'Minutos'}, {'id_indicador': 10450, 'nombre_indicador': 'TIEMPO PROMEDIO DE ESPERA PARA LA ATENCION EN URGENCIAS DEL PACIENTE CLASIFICADO COMO TRIAGE II (UFZ)', 'id_proceso': 1, 'id_objetivo': 4, 'frecuencia': 'Mensual', 'meta': None, 'unidad': 'Minutos'}]]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

In [82]:
df_obj.head()

,codigo_objetivo,nombre_objetivo,id_objetivo
16,",,,","Atención centrada en el usuario,Oportunidad,Pr...",1
18,",,,","Gestión clínica excelente y segura,Prestación ...",2
20,",,","Integral (el manejo),Prestación de Servicios,E...",3
26,",,,","Atención centrada en el usuario,Accesibilidad,...",4

In [83]:
df_obj.to_sql('objetivos_estrategicos', con=engine, if_exists='append', index=False)

4

In [86]:
df_indicadores = df_indicadores.drop_duplicates(subset=['id_indicador'])

In [87]:
df_indicadores.to_sql('indicadores', con=engine, if_exists='append', index=False)

12

In [88]:
df_areas = df[['Unidad auditable']].drop_duplicates()

In [89]:
df_areas = df_areas.dropna()

In [90]:
df_areas = df_areas.rename(columns={
    'Unidad auditable': 'nombre_area'
})

In [91]:
df_areas['id_area'] = range(1, len(df_areas)+1)

In [92]:
df_areas = df_areas[['id_area', 'nombre_area']]

In [93]:
df_areas.head()

     id_area                        nombre_area
8          1      Gestión Servicio de Urgencias
117        2  Gestión Servicio de Urgencias UFZ

In [94]:
df_areas.to_sql('areas', con=engine, if_exists='append', index=False)

2